### ISSUE TITLE
Hellbeast trait crashes game when hurt by blocks/not mobs

### ISSUE THREAD

**Issue by Thepigemperor2** [Lance5057/Tinkers-Compendium#185]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.4.jar)
  midnight (themidnight-0.3.4.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
  CreativePatchingLoader (CreativeCore_v1.9.69_mc1.12.2.jar)
  IGCMPatchingLoader (IGCM_v1.2.10_mc1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.2-core.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 9/12/20 5:29 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at lance5057.tDefense.core.materials.traits.TraitBurnAttacker.onDamageTaken(TraitBurnAttacker.java:14)
	at lance5057.tDefense.core.tools.TDToolEvents.playerDamagedEvent(TDToolEvents.java:160)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2202_TDToolEvents_playerDamagedEvent_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1120)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:918)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.entity.Entity.func_70044_A(Entity.java:532)
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:497)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:226)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2096)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at lance5057.tDefense.core.materials.traits.TraitBurnAttacker.onDamageTaken(TraitBurnAttacker.java:14)
	at lance5057.tDefense.core.tools.TDToolEvents.playerDamagedEvent(TDToolEvents.java:160)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2202_TDToolEvents_playerDamagedEvent_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1120)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:918)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.entity.Entity.func_70044_A(Entity.java:532)
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:497)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:226)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2096)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 838
	Entity Name: thepigemperor2
	Entity's Exact location: 157.87, 92.18, -23.93
	Entity's Block location: World: (157,92,-24), Chunk: (at 13,5,8 in 9,-2; contains blocks 144,0,-32 to 159,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -1.14, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@7e2cdf5a
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by P3rf3ctXZer0** [comment]
Can confirm.
