### ISSUE TITLE
Crash when picking up breastplate

### ISSUE THREAD

**Issue by Nosrick** [Lance5057/Tinkers-Compendium#89]
So this only seems to happen when I try to pick up the constructed breastplate, and it only started happening after I wore it for the first time. Shift + clicking gets it on and off just fine.

The breastplate is constructed from a few different materials. It has a bronze filigree, copper armour plate, bronze large plate (which I think has nulled out), iron chainmail and wool fabric. It has low durability for its construction, at 477 durability.

Here's the exception that caused the crash.
`[14:37:46] [Netty Client IO #2/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[MessageToByteEncoder.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:548) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [SingleThreadEventExecutor.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [NioEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at java.io.DataOutputStream.writeUTF(Unknown Source) ~[?:1.8.0_181]
	at java.io.DataOutputStream.writeUTF(Unknown Source) ~[?:1.8.0_181]
	at io.netty.buffer.ByteBufOutputStream.writeUTF(ByteBufOutputStream.java:137) ~[ByteBufOutputStream.class:4.1.9.Final]
	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:473) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:112) ~[gi.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:102) ~[gi.class:?]
	at net.minecraft.network.PacketBuffer.func_150786_a(PacketBuffer.java:288) ~[gy.class:?]
	at net.minecraftforge.common.util.PacketUtil.writeItemStackFromClientToServer(PacketUtil.java:56) ~[PacketUtil.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148840_b(CPacketClickWindow.java:58) ~[lf.class:?]
	at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:51) ~[ha.class:?]
	at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:12) ~[ha.class:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[MessageToByteEncoder.class:4.1.9.Final]
	... 18 more`

**Comment by Lance5057** [comment]
This should be fixed in the latest update.
